### ISSUE TITLE
Exception Handling / Unit Testing sprint, track activity here

### ISSUE THREAD

**Issue by rvandemark** [jporter7/YCP-RT-ControlRoom#175]
This is the one-and-only issue dedicated to tracking the activity of each of us during the EHUT sprint. We are aware of what classes we should each be extensively unit-testing (there's a picture in the control_room channel on Slack), so here, we should log which files we are modifying to add exception handling. Simply added a comment on here that contains a list of the files that you're adding exception handling to! Don't include files in the ControlRoomApplicationTests project.

**DUE DATE**: Your pull request should be in by 9PM on March 27th, PLEASE NO EXCEPTIONS (For Jason's sake, as he's the one handling pull requests). When making your pull request, be sure to follow the guidelines for it, as seen below (and again, please feel free to add anything if you see it fit):

**1.** Be very decisive about what branch you work in and commit to. You shouldn't work in a branch that someone is actively working in, it can create confusion. You can if the active parties are actively communicating though! Like what files are being modified by who, etcetera.
**2.** Always test your local commits before pushing to remote. Even if it's just a little change, it can't hurt to retest it. This means running in and the tests. This can cause a lot of problems if this isn't practiced, and Git is a little sensitive so it can be hard to repair.
**3.** When requesting to merge back into a significant branch like `master`, or in our case, something like `Development`, try to ease the efforts of the one approving the pull request by doing the following:
    **a.** Follow steps 1 and 2, above, and commit your changes to your remote branch.
    **b.** Pull and merge from `Development` into your local branch. If it doesn't build or run properly, then figure it out and talk with others as necessary!
    **c.** Once everything is working as expected, commit again if you need to, then create a pull request into `Development`.
**4.** Delete branches once you're done with them. For example, later tonight, I'll be deleting the `ControlRoomImprovements`and `HardwareInterfaces` branches. I'll be making some that are more specific now that the major overhaul is done, like `WeatherStation` and `SimulatedMCU` probably.

**Comment by rvandemark** [comment]
Modifying:
RadioTelescopeControllerManagementThread

**Comment by tjones50** [comment]
Modifying:
CoordinateCalculationController

**Comment by jporter7** [comment]
Modifying/testing:
- RTDbContext
- RFData
- ControlRoom
- RTDbConfiguration
- Configurations
- HeartbeatInterface
- SpectraCyberTestController

**Comment by dhenry5** [comment]
PLCsafteyInterlockStatusConversionHelper
PLCradiotelescopestatusconversionhelper
PLCLimitSwitchStatusConversionHelper
