### ISSUE TITLE
Create a timer for PLC connection

### ISSUE THREAD

**Issue by jporter7** [jporter7/YCP-RT-ControlRoom#81]
Create a timer that will "time-out" and close the TCP connection to the PLC if it is idle for too long.

**Comment by rvandemark** [comment]
Just saw this. I'll be sure to add this.

**Comment by rvandemark** [comment]
Actually, I misread what you initially meant - I don't think we should have the PLC ever terminate its TCP connection, having to coordinate when its down and bringing it back sounds unnecessary. If you feel strongly about this, please feel free to reopen this and I'd be happy to talk about it :)
