### ISSUE TITLE
Refactor and verify control room control loop

### ISSUE THREAD

**Issue by jporter7** [jporter7/YCP-RT-ControlRoom#89]
Refactor and verify the control room control loop that is found in the ControlRoomController class. This mostly has to do with the threading of the PLC and SpectraCyber and the main function that will need editing is StartAppointment().
The control loop should:
- Wait for an appointment
- Calibrate the radiotelescope
- Transform the coordinate from the appt into a set of orientations (RA, Dec)
- Spawn a thread to complete the movements of the RT
- Spawn a thread to complete the RFData gathering from the SpectraCyber
- Return the RT to the stow position
- Loop back to the beginning

**Comment by tjones50** [comment]
I refactored the main control loop. Note: I added test lines to generate an appointment that will need to be removed later
